### GENERAL SETTINGS ###

# Site settings
title: Snowflake Analytics
description: "Snowflake Anlaytics exists to make organisations better understand their businesses by enabling all decision makers in a company to work with the same version of the truth."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "snowflake-analytics.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#21406f" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: github
    url: https://github.com/snowflake-analytics
  - title: twitter
    url: https://twitter.com/snowflake_data
  - title: linkedin
    url: https://www.linkedin.com/company/snowflake-analytics

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - 3/ 1-9 Buckingham Street
    - Surry Hills, 2010, Surry Hills,
    - NSW, Australia
email: contact@snowflake-analytics.com
tel: +34 8493-4893


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Clients information. Shown on Home and About pages.
clients:
  - name: Australian Broadcasting Corporation
    img: 02.png
  - name: Fairfax Media
    img: 03.png
  - name: Deputy
    img: 04.png
  - name: CrownBet
    img: 07.png
  - name: The Iconic
    img: 09.png
  - name: Australian Radio Netowrk
    img: 11.png

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: " We exist to make organisations better understand their businesses by enabling all decision makers in a company to work with the same version of the truth."
